title: SmTHmIoT
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
baseurl: ""
url: "https://smthmiot.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Galler-ist # add your name
author-img: galler-ist.png # add your photo
about-author: This is Smart Home project page. I am "galler-ist" who likes board games.
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: SmtHmIoT # add your Github handle
social-notion: https://habitual-sawfish-65b.notion.site/PJT-c0507b313564419ea1667698be74759e # notion example
social-email: swghj0609@gmail.com # add your Email address
# social-linkedin: # add your Linkedin handle

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# basic layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
