title: SmTHmIoT
description: > # this means to ignore newlines until "baseurl:"

permalink: /:categories/:title/
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
baseurl: ""
url: "https://smthmiot.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: SmtHmIoT # add your name
author-img: Raspberry-Pi-Photo.jpg # add your photo
about-author: This is a Smart Home IoT system that checks the home environment using four sensors - humidity, temperature, sound, and light. It adjusts these values for optimal living conditions.
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: SmtHmIoT # add your Github handle
social-notion: https://www.naver.com # notion example
social-email: swghj0609@gmail.com # add your Email address
# social-linkedin: # add your Linkedin handle

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# basic layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
